<?php # -*- coding: utf-8 -*-
declare( strict_types = 1 );

namespace Bueltge\Marksimple\Rule;

interface ElementRuleInterface
{

    /**
     * @return string    RegEx rule
     */
    public function rule(): string;

    /**
     * @param  array     context which is generated by RegEx rule.
     * @return string    rendered element.
     */
    public function render(array $content): string;
}